#!/bin/bash
# 作者：老徐
# SSR免费分享网站（所有帐号均来源于网上别人的分享）：http://ssr.pythonic.life
# 源代码主页：https://github.com/the0demiurge
# 访问https://github.com/the0demiurge/CharlesScripts/blob/master/charles/bin/ssr获取本脚本的最新版
# 使用方法：把该脚本放到$PATH里面并加入可执行权限就行（比如说放到/usr/local/bin）
# 首次使用输入ssr install后安装时会自动安装到 $HOME/.local/share/shadowsocksr
# 输入ssr config进行配置，输入JSON格式的配置文件
# 输入ssr uninstall卸载
# 输入ssr help 展示帮助信息

set -e
if [ -z $EDITOR ];then
    EDITOR=vi
fi

BRANCH=manyuser
GIT_REPO=https://github.com/shadowsocksr-backup/shadowsocksr.git
INSTALL_PATH=$HOME/.local/share/shadowsocksr
PID_FILE=/tmp/ssr.pid
LOG_FILE=/tmp/ssr.log
PY_SCRIPT=ssr.py

ssr_help() {
    echo ShadowSocksR python client tool
    echo -e if you have not install ssr, please run \"ssr install\"
    echo Usage:
    echo -e "\t" "ssr help"
    echo -e "\t" "ssr install      install shadowsocksr client"
    echo -e "\t" "ssr uninstall    uninstall shadowsocksr client"
    echo -e "\t" "ssr config       edit config.json"
    echo -e "\t" "ssr cat          cat config.json"
    echo -e "\t" "ssr xclip        paste configs from clipboard to config.json"
    echo -e "\t" "ssr start        start the shadowsocks service"
    echo -e "\t" "ssr stop         stop the shadowsocks service"
    echo -e "\t" "ssr restart      restart the shadowsocks service"
    echo -e "\t" "ssr test         get ip from ip.cn using socks5 proxy"
    echo -e "\t" "ssr log          cat the log of shadowsocks"
    echo -e "\t" "ssr rss          cat the rss of shadowsocks"
    echo -e "\t" "ssr qr           generate qr-code"
}

ssr_install() {
    git clone -b $BRANCH $GIT_REPO $INSTALL_PATH
}

ssr_uninstall() {
    echo "Danger! are you to remove $INSTALL_PATH forever?(y/N)"
    read doit
    if [ $doit == 'y' ];then rm -rvf $INSTALL_PATH;fi
}

ssr_test(){
    echo Testing Connection...
    curl ip.cn --socks5 'localhost:1081'
}

ssr_start() {
    cd $INSTALL_PATH/shadowsocks/
    python ${PY_SCRIPT} -d start --pid-file $PID_FILE --log-file $LOG_FILE $@
    sleep 1
    ssr_test
}

ssr_stop() {
    cd $INSTALL_PATH/shadowsocks/
    python local.py -d stop --pid-file $PID_FILE --log-file $LOG_FILE 
}

ssr_restart() {
    ssr_stop
    ssr_start $@
}

ssr_config() {
    $EDITOR $INSTALL_PATH/config.json
    ssr_restart
}

ssr_xclip() {
    xclip -o|tee $INSTALL_PATH/config.json
    ssr_restart
}

ssr_cat()
{
	cat $INSTALL_PATH/config.json
}
ssr_log() {
    tail -f /tmp/shadowsocksr.log
}
ssr_rss() {
	ssrfile=freessr.txt
	ssrlist=freessr.list
	cd $INSTALL_PATH/
	for fn in https://ssrshare.xyz/freessr https://yzzz.ml/freessr https://raw.githubusercontent.com/ImLaoD/sub/master/ssrshare.com
	do
		curl -L $fn  | base64 -d |grep ^ssr >> $ssrfile
	done
	sort -u $ssrfile > $ssrlist
	cat $ssrlist
}


ssr_main() {
	str_type=$1;
	shift 
    case $str_type in
        help|install|uninstall|rss|config|cat|xclip|start|stop|restart|test|log)           ssr_${str_type}     $@   ;;
        *) ssr_help ;;
    esac
}

ssr_main $@


